### ISSUE TITLE
Exception when loading WAV-files

### ISSUE THREAD

**Issue by postlund** [beetbox/mediafile#49]
Whenever I try to load a WAV file I get this exception:

```raw
>>> import mediafile
>>> mediafile.MediaFile("file_example_WAV_1MG.wav")Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/postlund/pyatv_dev/pyatv/lib/python3.8/site-packages/mediafile.py", line 163, in wrapper    return mutagen_call('loadfile', '', f, *args, **kwargs)
  File "/home/postlund/pyatv_dev/pyatv/lib/python3.8/site-packages/mediafile.py", line 135, in mutagen_call
    return func(*args, **kwargs)
  File "/home/postlund/pyatv_dev/pyatv/lib/python3.8/site-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/home/postlund/pyatv_dev/pyatv/lib/python3.8/site-packages/mediafile.py", line 1595, in __init__
    raise FileTypeError(self.filename, type(self.mgfile).__name__)
mediafile.FileTypeError: 'file_example_WAV_1MG.wav': of mutagen type WAVE
```
Loading it in mutagen directly seems to work fine though:
```raw
>>> import mutagen
>>> mutagen.File("file_example_WAV_1MG.wav")
{'TCON': TCON(encoding=<Encoding.LATIN1: 0>, text=['Cinematic']), 'TALB': TALB(encoding=<Encoding.LATIN1: 0>, text=['YouTube Audio Library']), 'TIT2': TIT2(encoding=<Encoding.LATIN1: 0>, text=['Impact Moderato']), 'TPE1': TPE1(encoding=<Encoding.LATIN1: 0>, text=['Kevin MacLeod'])}
```
I'm using [this](https://file-examples-com.github.io/uploads/2017/11/file_example_WAV_1MG.wav) file as an example, but the same thing happens with other WAV files too.

**Comment by sampsyo** [comment]
MediaFile does not yet support WAV files. There's more detail/history in https://github.com/beetbox/beets/issues/2300. Any help adding support would be appreciated!

**Comment by postlund** [comment]
Oh, I see! Took a quick stab at it and it and it was easy enough, since mutagen adds ID3 tags which is already supported. What I need to do is to add tests. Do you have any good sources for test files I can use? Opened #50 in the meantime.

**Comment by postlund** [comment]
And right, example with PR applied:

```python
import mediafile
a= mediafile.MediaFile("sample.wav")
print([f"{f}={getattr(a, f)}" for f in a.fields() if getattr(a, f)])
```
Which yields:

```python 
['title=Impact Moderato', 'artist=Kevin MacLeod', 'album=YouTube Audio Library', "genres=['Cinematic']", 'genre=Cinematic']
```
Which is as expected.
